% Generation of Signals 
clc; 
clear all; 
close all; 
n=-3:3; 
i=[zeros(1,3) ones(1,1) zeros(1,3)]; subplot(2,3,1); 
stem(n,i); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Unit Impulse Function'); 
u=[zeros(1,3) ones(1,4)]; 
subplot(2,3,2); 
stem(n,u); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Unit Step Function'); 
n=0:5; 
subplot(2,3,3); 
stem(n,n); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Ramp Function');
n=0:0.01:1; 
s=sin(2*pi*n); 
subplot(2,3,4); 
stem(n,s); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Sine Function'); 
n=0:0.01:1; 
c=cos(2*pi*n); 
subplot(2,3,5); 
stem(n,c); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Cosine Function'); 
n=0:5; 
e=exp(-n); 
subplot(2,3,6); 
stem(n,e); 
xlabel('n'); 
ylabel('Amplitude'); 
title('Exponential Function');

